###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
  mysql:
    image: 'mysql:8.0'
    working_dir: /application
    volumes:
        - '.:/application'
    environment:
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_DATABASE=cardgame
        - MYSQL_USER=cardgame
        - MYSQL_PASSWORD=cardgame
    ports:
        - '58002:3306'
  webserver-ft:
    image: 'nginx:alpine'
    working_dir: /application
    volumes:
      - '.:/application'
      - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '12001:80'

  php-fpm-ft:
    build: phpdocker/php-fpm
    working_dir: /application
    volumes:
      - '.:/application'
      - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'
